version: "3.7"

services:
  nb_ore:
      build:
        context: .
        dockerfile: Dockerfile
      image: nb_ore
      container_name: nb_ore
      environment:
        TZ: "America/new_york"
      ports:
        - "8282:8282"
      volumes:
        - /data/code/projects/notebook:/home/jupyter/notebook
        - /etc/localtime:/etc/localtime:ro
